BenchmarkBibleVerse/Models/BibleVerseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BenchmarkBibleVerse.Models
{
    public class BibleVerseModel
    {
        [Required]
        [Display(Name ="Testament:")]
        [StringLength(3, MinimumLength =3)]
        public string Testament { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Book:")]
        public string BookSelection { get; set; }
        
        [Required]
        [Range(1,1000)]
        [Display(Name = "Chapter:")]
        public int ChapterSelect { get; set; }
        
        [Required]
        [Range(1,1000)]
        [Display(Name = "Verse #:")]
        public int VerseNumber { get; set; }
        
        [Required]
        [MinLength(1)]
        [Display(Name = "Verse:")]
        public string VerseString { get; set; }
    }
}

BenchmarkBibleVerse/Controllers/BibleVerseEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using BenchmarkBibleVerse.Models;
using BenchmarkBibleVerse.Service.Business;
using BenchmarkBibleVerse.Service.Utility;

namespace BenchmarkBibleVerse.Controllers
{
    public class BibleVerseEntryController : Controller
    {
        /*
         * Creates logger and receives it using dependency injection
         */
        private readonly ILogger logger;
        public BibleVerseEntryController(ILogger logger)
        {
            this.logger = logger;
        }

        // GET: BibleVerseEntry
        public ActionResult Index()
        {
            logger.Info("Action Index invoked from the BibleVerseEntry controller.");
            return View("CreateVerse");
        }

        [HttpPost]
        public ActionResult CreateVerse(BibleVerseModel verse)
        {
            /*
             * Checks if the model passed and returns validation errors if invalid
             */
            if(ModelState.IsValid){
                /*
                 * Tries to write verse to database.
                 * Clears model before returning view
                 */
                logger.Info("Bible verse with parameters " + new JavaScriptSerializer().Serialize(verse) + " is being created. BibleVerseModel ModelState is valid.");
                BibleVerseService service = new BibleVerseService(logger);
                try
                {
                    service.AddVerse(verse);
                    logger.Info("Bible verse with parameters " + new JavaScriptSerializer().Serialize(verse) + " has been successfully saved to the database.");
                }
                catch (Exception ex)
                {
                    logger.Error("Exception has occured. Exception " + ex.Message);
                }
                ModelState.Clear();
            } else
            {
                logger.Warning("Bible verse with parameters " + new JavaScriptSerializer().Serialize(verse) + " is being not being created. BibleVerseModel ModelState is invalid");
            }
            
            return View("CreateVerse");

        }


        public ActionResult SearchVerse()
        {
            logger.Info("Action SearchVerse from BibleVerseEntry controller has been invoked.");
            return View("SearchVerse");
        }

        [HttpGet]
        public ActionResult GetVerse(BibleVerseModel verse)
        {
            /*
             * Tries to retrieve verse from database
             */
            logger.Info("Search request for verse " + new JavaScriptSerializer().Serialize(verse) + " executing.");
            BibleVerseService service = new BibleVerseService(logger);
            try
            {
                verse = service.GetVerse(verse);
            } catch (Exception ex)
            {
                logger.Error("Exception occured searching for verse " + new JavaScriptSerializer().Serialize(verse) + "\nException: " + ex.Message);
            }

            /*
             * Creates different logs if the verse was successfully retrieved from the database
             */
            if(verse.VerseString == null || verse.VerseString == "")
            {
                logger.Warning("No verse was found for " + new JavaScriptSerializer().Serialize(verse));
            } else
            {
                logger.Info("Search request completed successfully.");
            }
            return View("SearchVerse", verse);
            
        }
        
    }
}

BenchmarkBibleVerse/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BenchmarkBibleVerse.Service.Utility;

namespace BenchmarkBibleVerse.Controllers
{
    public class HomeController : Controller
    {

        /*
         * Creates logger and receives it using dependency injection
         */
        private ILogger logger;
        
        public HomeController(ILogger logger)
        {
            this.logger = logger;
        }
        // GET: Home
        public ActionResult Index()
        {
            logger.Info("Action Index in Home controller has been invoked.");
            return View("Home");
        }
    }
}

BenchmarkBibleVerse/Views/BibleVerseEntry/CreateVerse.cshtml
@model BenchmarkBibleVerse.Models.BibleVerseModel

@{
    ViewBag.Title = "CreateVerse";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

<div class="formcenter">
<h2 class="titlecenter">Create Verse</h2>
<br />

@using (Html.BeginForm("CreateVerse", "BibleVerseEntry", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.Label("Old:", new { @class = "customradiolabels" })
            @Html.RadioButtonFor(model => model.Testament, "Old")
            @Html.Label("New:", new { @class = "customradiolabels" })
            @Html.RadioButtonFor(model => model.Testament, "New")
            @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookSelection, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookSelection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookSelection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterSelect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterSelect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterSelect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.VerseString, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.VerseString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BenchmarkBibleVerse/Views/BibleVerseEntry/CreateView.cshtml
@model BenchmarkBibleVerse.Models.BibleVerseModel

@{
    ViewBag.Title = "CreateView";
}

<h2>CreateView</h2>


@using (Html.BeginForm("CreateVerse", "BibleVerseEntry", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BibleVerseModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            <br/>
            @Html.Label("Old")@Html.RadioButtonFor(model => model.Testament, "Old")
            @Html.Label("New")@Html.RadioButtonFor(model => model.Testament, "New")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookSelection, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookSelection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookSelection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterSelect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterSelect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterSelect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.VerseString, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BenchmarkBibleVerse/Views/BibleVerseEntry/SearchVerse.cshtml
@model BenchmarkBibleVerse.Models.BibleVerseModel

@{
    ViewBag.Title = "SearchVerse";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}



<div class="formcenter">
    <h2 class="titlecenter">Search Verse</h2>
    <br />
    @using (Html.BeginForm("GetVerse", "BibleVerseEntry", FormMethod.Get))
    {
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.Testament, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Label("Old:")
            @Html.RadioButtonFor(model => model.Testament, "Old")
            @Html.Label("New:", new { @class = "customradiolabels" })
            @Html.RadioButtonFor(model => model.Testament, "New")
            @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BookSelection, new { @class = "control-label col-md-2" })
        <div class="col-mod-10">
            @Html.TextBoxFor(model => model.BookSelection, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BookSelection, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ChapterSelect, new { @class = "control-label col-md-2" })
        <div class="col-mod-10">
            @Html.TextBoxFor(model => model.ChapterSelect, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ChapterSelect, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.VerseNumber, new { @class = "control-label col-md-2" })
        <div class="col-mod-10">
            @Html.TextBoxFor(model => model.VerseNumber, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}

@if (Model != null && Model.VerseString != null && Model.VerseString != "")
{
    <hr />
    @Html.DisplayNameFor(model => model.VerseString)
    <br />
    @Html.LabelFor(model => model.VerseString, Model.VerseString, new { @class = "versecenter" })
}
else if (Model != null && Model.BookSelection != null && Model.BookSelection != "" && (Model.VerseString == null || Model.VerseString == ""))
{
    <hr />
    <label>No results found.</label>
}

</div>

BenchmarkBibleVerse/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

<body>
    <div>
        <h2 class="logoheadersh2">Welcome to Verses!</h2>
        <h4 class="logoheadersh4">Search for your favorite bible verses</h4>
    </div>
</body>

BenchmarkBibleVerse/Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Content/Custom/HomePage.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Add Verse", "Index", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Find Verse", "SearchVerse", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <div style="position:absolute; bottom:0px; width: 60%">
            <hr />
            <footer class="homefooter" >
                <p>&copy; @DateTime.Now.Year - Verses</p>
            </footer>
        <div />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

BenchmarkBibleVerse/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Content/HomePage.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Add Verse", "Index", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Find Verse", "SearchVerse", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <div style="position:absolute; bottom:0px; width: 60%">
            <hr />
            <footer >
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        <div />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

BenchmarkBibleVerse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Add Bible Verse", "Index", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Find Bible Verse", "SearchVerse", "BibleVerseEntry", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <div style="position:absolute; bottom:0px; width: 60%">
            <hr />
            <footer >
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        <div />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>